INSERT INTO `programs` (`id`, `name`, `college_id`, `honor_id`, `description`) VALUES
('accounting', 'ACCOUNTING', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('accounting-and-finance', ' ACCOUNTING & FINANCE ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('actuarial-science', ' ACTUARIAL SCIENCE ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('adult-and-community-education', ' ADULT & COMMUNITY EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('adult-and-continuous-education', 'ADULT AND CONTINUOUS EDUCATION', 4, 1, 'asdfghj'),
('adult-and-non-formal-education', ' ADULT & NON-FORMAL EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('adult-education', ' ADULT EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('adult-education-and-community-development', ' ADULT EDUCATION & COMMUNITY DEVELOPMENT ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('adult-education-economics-and-statistics', ' ADULT EDUCATION / ECONOMICS & STATISTICS ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('adult-education-english-literature', ' ADULT EDUCATION / ENGLISH LITERATURE ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('adult-education-geography-and-regional-planning', ' ADULT EDUCATION / GEOGRAPHY & REGIONAL PLANNING ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('adult-education-political-science-and-public-administration', ' ADULT EDUCATION / POLITICAL SCIENCE & PUBLIC ADMINISTRATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('aeronautic-and-astronautic-engineering', ' AERONAUTIC & ASTRONAUTIC ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('aerospace-engineering', ' AEROSPACE ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('african-and-asian-studies', ' AFRICAN & ASIAN STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('african-traditional-religion', 'AFRICAN TRADITIONAL RELIGION', 3, 1, ''),
('agribusiness-management', 'AGRI-BUSINESS MANAGEMENT', 2, 1, ''),
('agric-business', ' AGRIC BUSINESS ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agric-economics-and-extension', ' AGRIC-ECONOMICS & EXTENSION ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agric-extension-and-rural-sociology', ' AGRIC-EXTENSION & RURAL SOCIOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agric-extension-service', ' AGRIC EXTENSION SERVICE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agricultural-administration', ' AGRICULTURAL ADMINISTRATION ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agricultural-and-bioresources-engineering', ' AGRICULTURAL & BIORESOURCES ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agricultural-and-biosystems-engineering', ' AGRICULTURAL & BIOSYSTEMS ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agricultural-and-environmental-engineering', ' AGRICULTURAL & ENVIRONMENTAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agricultural-economics', ' AGRICULTURAL ECONOMICS ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agricultural-economics-and-farm-management', ' AGRICULTURAL ECONOMICS & FARM MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agricultural-engineering', ' AGRICULTURAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agricultural-extension', ' AGRICULTURAL EXTENSION ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agricultural-extension-and-communication-technology', ' AGRICULTURAL EXTENSION & COMMUNICATION TECHNOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agricultural-extension-and-management', ' AGRICULTURAL EXTENSION & MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agricultural-extension-and-rural-development', ' AGRICULTURAL EXTENSION & RURAL DEVELOPMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agricultural-extension-and-social-engineering', 'AGRICULTURAL EXTENTION AND SOCIAL ENGINEERING', 1, 1, ''),
('agricultural-production-and-management-science-and-education', ' AGRICULTURAL PRODUCTION & MANAGEMENT SCIENCE & EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agricultural-science-and-education', ' AGRICULTURAL SCIENCE & EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agriculture', ' AGRICULTURE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('agronomy', ' AGRONOMY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('anatomy', ' ANATOMY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-and-environmental-biology', ' ANIMAL & ENVIRONMENTAL BIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-biology-and-environment', ' ANIMAL BIOLOGY & ENVIRONMENT ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-breeding-and-genetics', ' ANIMAL BREEDING & GENETICS ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-nutrition', ' ANIMAL NUTRITION ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-nutrition-and-biotechnology', ' ANIMAL NUTRITION & BIOTECHNOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-physiology', ' ANIMAL PHYSIOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-production', ' ANIMAL PRODUCTION ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-production-and-fisheries', ' ANIMAL PRODUCTION & FISHERIES ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-production-and-health', ' ANIMAL PRODUCTION & HEALTH ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-production-and-health-services', ' ANIMAL PRODUCTION & HEALTH SERVICES ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-science', ' ANIMAL SCIENCE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-science-and-fisheries', ' ANIMAL SCIENCE & FISHERIES ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-science-and-fisheries-management', ' ANIMAL SCIENCE & FISHERIES MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-science-and-range-management', ' ANIMAL SCIENCE & RANGE MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('animal-science-and-technology', ' ANIMAL SCIENCE & TECHNOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('anthropology', ' ANTHROPOLOGY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('anthropology-biological', ' ANTHROPOLOGY-BIOLOGICAL', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('applied-biochemistry', ' APPLIED BIOCHEMISTRY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('applied-biology', ' APPLIED BIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('applied-biology-and-biotechnology', ' APPLIED BIOLOGY & BIOTECHNOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('applied-biology-and-genetics', ' APPLIED BIOLOGY & GENETICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('applied-botany', ' APPLIED BOTANY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('applied-chemistry', ' APPLIED CHEMISTRY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('applied-ecology', ' APPLIED ECOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('applied-geology', ' APPLIED GEOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('applied-geophysics', ' APPLIED GEOPHYSICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('applied-mathematics-with-statistics', ' APPLIED MATHEMATICS WITH STATISTICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('applied-microbiology', ' APPLIED MICROBIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('applied-microbiology-and-brewing', ' APPLIED MICROBIOLOGY & BREWING ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('applied-physics', ' APPLIED PHYSICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('applied-statistics', 'APPLIED STATISTICS', 8, 1, ''),
('applied-zoology', ' APPLIED ZOOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('aquaculture-and-fisheries-management', ' AQUACULTURE & FISHERIES MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('arabic-and-islamic-studies', ' ARABIC & ISLAMIC STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('arabic-language-and-literature', ' ARABIC LANGUAGE & LITERATURE ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('arabic-studies', ' ARABIC STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('archaeology', ' ARCHAEOLOGY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('architecture', ' ARCHITECTURE ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('arts', ' ARTS-COMBINED HONOURS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('automobile-engineering', ' AUTOMOBILE ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('automotive-engineering', ' AUTOMOTIVE ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('b.a', ' B.A. SINGLE & COMBINED HONS IN MODERN LANGUAGES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('banking-and-finance', ' BANKING & FINANCE ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('biochemistry', ' BIOCHEMISTRY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('biochemistry-and-molecular-biology', ' BIOCHEMISTRY & MOLECULAR BIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('bioinformatics', ' BIOINFORMATICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('biological-sciences', ' BIOLOGICAL SCIENCES ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('biology', ' BIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('biomedical-engineering', ' BIOMEDICAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('biomedical-technology', ' BIOMEDICAL TECHNOLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('biostatistics', 'BIOSTATISTICS', 8, 1, ''),
('biotechnology', ' BIOTECHNOLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('botany', ' BOTANY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('botany-and-ecological-studies', ' BOTANY & ECOLOGICAL STUDIES ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('building', ' BUILDING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('building-technology', ' BUILDING TECHNOLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('business-administration', ' BUSINESS ADMINISTRATION ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('business-and-entrepreneurship-studies', ' BUSINESS & ENTREPRENEURSHIP STUDIES ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('business-education', ' BUSINESS EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('business-management', ' BUSINESS MANAGEMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('business-management-management-science', ' BUSINESS MANAGEMENT / MANAGEMENT SCIENCE ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('cell-biology-and-genetics', ' CELL BIOLOGY & GENETICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('chemical-and-petroleum-engineering', 'CHEMICAL AND PETROLEUM ENGINEERING ', 5, 1, ''),
('chemical-and-polymer-engineering', ' CHEMICAL & POLYMER ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('chemical-engineering', ' CHEMICAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('chemical-petrochemical-engineering', ' CHEMICAL / PETROCHEMICAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('chemical-sciences', ' CHEMICAL SCIENCES ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('chemistry', ' CHEMISTRY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('chemistry-and-industrial-chemistry', ' CHEMISTRY & INDUSTRIAL CHEMISTRY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('chinese-studies', ' CHINESE STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('christian-religious-studies', ' CHRISTIAN RELIGIOUS STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('christian-theology', ' CHRISTIAN THEOLOGY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('civil-engineering', ' CIVIL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('civil-law', ' CIVIL LAW ', 6, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('classical-studies', ' CLASSICAL STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('common-and-islamic-law', ' COMMON & ISLAMIC LAW ', 6, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('common-law', ' COMMON LAW ', 6, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('communication-and-language-arts', ' COMMUNICATION & LANGUAGE ARTS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('communication-and-wireless-technology', ' COMMUNICATION & WIRELESS TECHNOLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('communication-arts', ' COMMUNICATION ARTS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('communication-technology', ' COMMUNICATION TECHNOLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('community-health', 'COMMUNITY HEALTH', 7, 1, ''),
('comparative-religious-studies', ' COMPARATIVE RELIGIOUS STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('computer-and-communication-engineering', ' COMPUTER & COMMUNICATION ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('computer-education', ' COMPUTER EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('computer-engineering', ' COMPUTER ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('computer-information-and-communication-science', ' COMPUTER, INFORMATION & COMMUNICATION SCIENCE ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('computer-science', ' COMPUTER SCIENCE ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('computer-science-and-informatics', ' COMPUTER SCIENCE & INFORMATICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('computer-science-and-information-science', ' COMPUTER SCIENCE & INFORMATION SCIENCE ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('computer-science-and-mathematics', ' COMPUTER SCIENCE & MATHEMATICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('computer-science-with-economics', ' COMPUTER SCIENCE WITH ECONOMICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('computer-science-with-economics-mathematics', ' COMPUTER SCIENCE WITH ECONOMICS AND MATHEMATICS ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('computer-science-with-mathematics', ' COMPUTER SCIENCE WITH MATHEMATICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('computer-with-electronics', ' COMPUTER WITH ELECTRONICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('computer-with-statistics', ' COMPUTER WITH STATISTICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('conflict-and-peace-resolution', ' CONFLICT & PEACE RESOLUTION ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('conservation-biology', ' CONSERVATION BIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('cooperative-and-rural-development', ' COOPERATIVE & RURAL DEVELOPMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('cooperative-economics-and-management', ' COOPERATIVE ECONOMICS & MANAGEMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('cooperative-management', ' COOPERATIVE MANAGEMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('counsellor-education', 'COUNCELLOR EDUCATION', 4, 2, ''),
('creative-and-visual-arts', ' CREATIVE & VISUAL ARTS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('creative-arts', ' CREATIVE ARTS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('criminology', ' CRIMINOLOGY ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('criminology-and-penology', ' CRIMINOLOGY & PENOLOGY ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('criminology-and-security-studies', ' CRIMINOLOGY & SECURITY STUDIES ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-and-environmental-protection', ' CROP & ENVIRONMENTAL PROTECTION ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-production', ' CROP PRODUCTION ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-production-and-horticulture', ' CROP PRODUCTION & HORTICULTURE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-production-and-landscape-management', ' CROP PRODUCTION & LANDSCAPE MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-production-and-protection', ' CROP PRODUCTION & PROTECTION ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-production-and-soil-science', ' CROP PRODUCTION & SOIL SCIENCE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-production-technology', ' CROP PRODUCTION TECHNOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-protection', ' CROP PROTECTION ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-science', ' CROP SCIENCE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-science-and-biotechnology', ' CROP SCIENCE & BIOTECHNOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-science-and-horticulture', ' CROP SCIENCE & HORTICULTURE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-science-and-production', ' CROP SCIENCE & PRODUCTION ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-science-and-technology', ' CROP SCIENCE & TECHNOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-soil-and-environmental-science', ' CROP SOIL & ENVIRONMENTAL SCIENCE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('crop-soil-and-pest-management', ' CROP SOIL & PEST MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('curriculum-and-instruction', ' CURRICULUM & INSTRUCTION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('curriculum-studies', ' CURRICULUM STUDIES ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('cyber-security', ' CYBER SECURITY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('cyber-security-science', ' CYBER SECURITY SCIENCE ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('data-management', ' DATA MANAGEMENT ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('defence-and-security-studies', 'DEFENCE AND SECURITY STUDIES', 9, 1, ''),
('demography-and-social-statistics', ' DEMOGRAPHY & SOCIAL STATISTICS ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('demography-and-statistics', ' DEMOGRAPHY & STATISTICS ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('dental-technology', ' DENTAL TECHNOLOGY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('dentistry-and-dental-surgery', ' DENTISTRY & DENTAL SURGERY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('doctor-of-pharmacy', ' DOCTOR OF PHARMACY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('drama-dramatic-performing-arts', ' DRAMA / DRAMATIC / PERFORMING ARTS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('early-childhood-and-primary-education', ' EARLY CHILDHOOD & PRIMARY EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('early-childhood-education', ' EARLY CHILDHOOD EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('earth-science', ' EARTH SCIENCE ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('ecology', ' ECOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('ecology-and-environmental-studies', ' ECOLOGY & ENVIRONMENTAL STUDIES ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('economics', ' ECONOMICS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('economics-and-development-studies', ' ECONOMICS & DEVELOPMENT STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('economics-and-statistics', ' ECONOMICS & STATISTICS ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('economics-geography-physics', ' ECONOMICS / GEOGRAPHY / PHYSICS ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('economics-with-operation-research', ' ECONOMICS WITH OPERATION RESEARCH ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('ecotourism-and-wildlife-management', ' ECOTOURISM & WILDLIFE MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-accounting', ' EDUCATION ACCOUNTING ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-arabic', ' EDUCATION & ARABIC ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-biology', ' EDUCATION & BIOLOGY ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-chemistry', ' EDUCATION & CHEMISTRY ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-christian-religious-studies', ' EDUCATION & CHRISTIAN RELIGIOUS STUDIES ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-computer-science', ' EDUCATION & COMPUTER SCIENCE ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-economics', ' EDUCATION & ECONOMICS ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-edo-language', ' EDUCATION & EDO LANGUAGE ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-efik-ibibio', ' EDUCATION & EFIK / IBIBIO ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-english-and-literary-studies', ' EDUCATION & ENGLISH & LITERARY STUDIES ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-english-language', ' EDUCATION & ENGLISH LANGUAGE ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-english-language-literature', ' EDUCATION & ENGLISH LANGUAGE LITERATURE ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-french', ' EDUCATION & FRENCH ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-geography', ' EDUCATION & GEOGRAPHY ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-government', ' EDUCATION & GOVERNMENT ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-hausa', ' EDUCATION & HAUSA ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-history', ' EDUCATION & HISTORY ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-igbo', ' EDUCATION & IGBO ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-integrated-science', ' EDUCATION & INTEGRATED SCIENCE ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-islamic-studies', ' EDUCATION & ISLAMIC STUDIES ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-mathematics', ' EDUCATION & MATHEMATICS ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-music', ' EDUCATION & MUSIC ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-physics', ' EDUCATION & PHYSICS ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-political-science', ' EDUCATION & POLITICAL SCIENCE ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-religious-studies', ' EDUCATION & RELIGIOUS STUDIES ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-science', ' EDUCATION & SCIENCE ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-social-science', ' EDUCATION & SOCIAL SCIENCE ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-social-studies', ' EDUCATION & SOCIAL STUDIES ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-sociology', ' EDUCATION & SOCIOLOGY ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-and-yoruba', ' EDUCATION & YORUBA ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-fine-art', ' EDUCATION / FINE ART ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-foundations-and-management', ' EDUCATION FOUNDATIONS & MANAGEMENT ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-language-and-french', ' EDUCATION LANGUAGE & FRENCH ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('education-mechanical', 'EDUCATION / MECHANICAL', 4, 1, ''),
('education-psychology-and-curriculum-studies', ' EDUCATION PSYCHOLOGY & CURRICULUM STUDIES ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('educational-administration', ' EDUCATIONAL ADMINISTRATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('educational-administration-and-planning', ' EDUCATIONAL ADMINISTRATION & PLANNING ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('educational-foundations', ' EDUCATIONAL FOUNDATIONS ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('educational-foundations-and-administration', ' EDUCATIONAL FOUNDATIONS & ADMINISTRATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('educational-management', ' EDUCATIONAL MANAGEMENT ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('educational-management-and-planning', ' EDUCATIONAL MANAGEMENT & PLANNING ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('educational-management-and-policy', ' EDUCATIONAL MANAGEMENT & POLICY ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('educational-psychology', 'EDUCATIONAL PSYCHOLOGY', 4, 1, ''),
('educational-psychology-guidance-and-counselling', ' EDUCATIONAL / PSYCHOLOGY GUIDANCE & COUNSELLING ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('efik-ibibio', ' EFIK-IBIBIO ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('electrical-and-computer-engineering', ' ELECTRICAL & COMPUTER ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('electrical-and-information-engineering', ' ELECTRICAL & INFORMATION ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('electrical-electronics-education', ' ELECTRICAL / ELECTRONICS EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('electrical-electronics-engineering', ' ELECTRICAL / ELECTRONICS ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('electrical-engineering', ' ELECTRICAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('electronics', ' ELECTRONICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('electronics-and-computer-engineering', ' ELECTRONICS & COMPUTER ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('electronics-and-computer-technology', ' ELECTRONICS & COMPUTER TECHNOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('electronics-engineering', ' ELECTRONICS ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('electrons', ' ELECTRONS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('elementary-education', ' ELEMENTARY EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('energy-and-petroleum-studies', ' ENERGY & PETROLEUM STUDIES ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('energy-studies', ' ENERGY STUDIES ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('engineering-physics', ' ENGINEERING PHYSICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('english-and-international-studies', ' ENGLISH & INTERNATIONAL STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('english-and-literary-studies', ' ENGLISH & LITERARY STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('english-language', ' ENGLISH LANGUAGE ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('english-language-and-communication-studies', ' ENGLISH LANGUAGE & COMMUNICATION STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('english-language-and-literature', ' ENGLISH LANGUAGE & LITERATURE ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('english-studies', ' ENGLISH STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('entrepreneurial-studies', ' ENTREPRENEURIAL STUDIES ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('entrepreneurship', ' ENTREPRENEURSHIP ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('entrepreneurship-and-business-management', ' ENTREPRENEURSHIP & BUSINESS MANAGEMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('entrepreneurship-studies-and-innovation', ' ENTREPRENEURSHIP STUDIES & INNOVATION ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-biology', ' ENVIRONMENTAL BIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-biology-and-fisheries', ' ENVIRONMENTAL BIOLOGY & FISHERIES ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-education', ' ENVIRONMENTAL EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-engineering', ' ENVIRONMENTAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-health-science', ' ENVIRONMENTAL HEALTH SCIENCE ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-management', ' ENVIRONMENTAL MANAGEMENT ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-management-and-pollution-control', ' ENVIRONMENTAL MANAGEMENT & POLLUTION CONTROL ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-management-and-toxicology', ' ENVIRONMENTAL MANAGEMENT & TOXICOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-management-technology', ' ENVIRONMENTAL MANAGEMENT TECHNOLOGY', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-protection-and-resources-management', ' ENVIRONMENTAL PROTECTION & RESOURCES MANAGEMENT ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-resources-management', ' ENVIRONMENTAL RESOURCES MANAGEMENT ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-science', ' ENVIRONMENTAL SCIENCE ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-science-and-technology', ' ENVIRONMENTAL SCIENCE & TECHNOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-science-resources-management', ' ENVIRONMENTAL SCIENCE RESOURCES MANAGEMENT ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('environmental-technology', ' ENVIRONMENTAL TECHNOLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('estate-management', ' ESTATE MANAGEMENT ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('estate-management-and-valuation', 'ESTATE MANAGEMENT AND EVALUATION', 5, 1, ''),
('european-and-nigerian-languages', ' EUROPEAN & NIGERIAN LANGUAGES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('exercise-and-sports-science', ' EXERCISE & SPORTS SCIENCE ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('family-nutrition-and-consumer-sciences', ' FAMILY NUTRITION & CONSUMER SCIENCES ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('film-and-video-studies', ' FILM & VIDEO STUDIES ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('finance', ' FINANCE ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('fine-and-applied-arts', ' FINE & APPLIED ARTS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('fine-and-industrial-arts', ' FINE & INDUSTRIAL ARTS ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('fine-art', ' FINE ART ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('fine-arts-and-design', ' FINE ARTS & DESIGN ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('fine-arts-fine-and-applied-arts', ' FINE ARTS / FINE & APPLIED ARTS ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('fisheries', ' FISHERIES ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('fisheries-and-aquaculture', ' FISHERIES & AQUACULTURE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('fisheries-and-aquaculture-technology', ' FISHERIES & AQUACULTURE TECHNOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('fisheries-and-aquatic-environment-management', ' FISHERIES & AQUATIC ENVIRONMENT MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('fisheries-and-aquatic-resources-management', ' FISHERIES & AQUATIC RESOURCES MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('fisheries-and-wildlife-management', ' FISHERIES & WILDLIFE MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('fisheries-management', ' FISHERIES MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('food-engineering', ' FOOD ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('food-science', ' FOOD SCIENCE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('food-science-and-engineering', ' FOOD SCIENCE & ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('food-science-and-technology', ' FOOD SCIENCE & TECHNOLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('food-science-with-business', ' FOOD SCIENCE WITH BUSINESS ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('forensic-science', ' FORENSIC SCIENCE ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('forestry', ' FORESTRY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('forestry-and-environmental-management', ' FORESTRY & ENVIRONMENTAL MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('forestry-and-resource-economics', 'FORESTRY AND RESOURCE ECONOMICS', 2, 1, ''),
('forestry-and-wildlife', ' FORESTRY & WILDLIFE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('forestry-and-wildlife-management', ' FORESTRY & WILDLIFE MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('forestry-and-wildlife-technology', ' FORESTRY & WILDLIFE TECHNOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('forestry-and-wood-technology', ' FORESTRY & WOOD TECHNOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('forestry-forest-resources-management', ' FORESTRY / FOREST RESOURCES MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('forestry-wildlife-and-fisheries', ' FORESTRY WILDLIFE & FISHERIES ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('french', ' FRENCH ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('french-and-international-relations', ' FRENCH & INTERNATIONAL RELATIONS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('french-and-international-studies', ' FRENCH & INTERNATIONAL STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('french-with-german-russian', ' FRENCH WITH GERMAN / RUSSIAN ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('fulfulde', ' FULFULDE ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('gas-engineering', ' GAS ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('genetics-and-biotechnology', ' GENETICS & BIOTECHNOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geography', ' GEOGRAPHY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geography-and-environmental-management', ' GEOGRAPHY & ENVIRONMENTAL MANAGEMENT ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geography-and-environmental-science', ' GEOGRAPHY & ENVIRONMENTAL SCIENCE ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geography-and-geosciences', ' GEOGRAPHY & GEOSCIENCES ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geography-and-meteorology', ' GEOGRAPHY & METEOROLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geography-and-planning', ' GEOGRAPHY & PLANNING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geography-and-planning-science', ' GEOGRAPHY & PLANNING SCIENCE ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geography-and-regional-planning', ' GEOGRAPHY & REGIONAL PLANNING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geological-sciences', ' GEOLOGICAL SCIENCES ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geology', ' GEOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geology-and-geophysics', ' GEOLOGY & GEOPHYSICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geology-and-mineral-science', ' GEOLOGY & MINERAL SCIENCE ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geology-and-mining', ' GEOLOGY & MINING ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geology-and-petroleum-studies', ' GEOLOGY & PETROLEUM STUDIES ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geophysics', ' GEOPHYSICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('geoscience', ' GEOSCIENCE ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('german', ' GERMAN ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('glass-technology', ' GLASS TECHNOLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('government-and-public-administration', ' GOVERNMENT & PUBLIC ADMINISTRATION ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('guidance-and-counselling', ' GUIDANCE & COUNSELLING ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('hausa', ' HAUSA ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('health-and-safety-education', ' HEALTH & SAFETY EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('health-education', ' HEALTH EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('history', ' HISTORY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('history-and-archeology', ' HISTORY & ARCHEOLOGY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('history-and-diplomacy', ' HISTORY & DIPLOMACY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('history-and-diplomatic-studies', ' HISTORY & DIPLOMATIC STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('history-and-international-relations', ' HISTORY & INTERNATIONAL RELATIONS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('history-and-international-studies', ' HISTORY & INTERNATIONAL STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('history-and-strategic-studies', ' HISTORY & STRATEGIC STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('history-sociology', ' HISTORY / SOCIOLOGY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('home-and-hotel-management', ' HOME & HOTEL MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('home-economics', ' HOME ECONOMICS ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('home-economics-and-education', ' HOME ECONOMICS & EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('home-economics-and-food-management', ' HOME ECONOMICS & FOOD MANAGEMENT ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('home-economics-and-hotel-management-and-education', ' HOME ECONOMICS & HOTEL MANAGEMENT & EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('home-economics-and-management-economics', ' HOME ECONOMICS & MANAGEMENT /ECONOMICS ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('home-science', ' HOME SCIENCE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('home-science-and-management', ' HOME SCIENCE & MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('home-science-nutrition-and-dietetics', ' HOME SCIENCE NUTRITION & DIETETICS ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('horticulture', ' HORTICULTURE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('horticulture-and-landscape-architecture', 'HORTICULTURE AND LANDSCAPE ARCHITECTURE', 5, 1, ''),
('hospitality-and-tourism', ' HOSPITALITY & TOURISM ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('hospitality-and-tourism-management', ' HOSPITALITY & TOURISM MANAGEMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('hotel-and-catering-management', ' HOTEL & CATERING MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('hotel-and-tourism-management', ' HOTEL & TOURISM MANAGEMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('hotel-management-and-tourism', ' HOTEL MANAGEMENT & TOURISM ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('human-anatomy', ' HUMAN ANATOMY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('human-biology', ' HUMAN BIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('human-kinetics', ' HUMAN KINETICS ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('human-kinetics-and-health-education', ' HUMAN KINETICS & HEALTH EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('human-nutrition-and-dietetics', ' HUMAN NUTRITION & DIETETICS ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('human-physiology', ' HUMAN PHYSIOLOGY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('human-resources-management', ' HUMAN RESOURCES MANAGEMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('igbo', ' IGBO ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-and-environmental-chemistry', ' INDUSTRIAL & ENVIRONMENTAL CHEMISTRY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-and-labour-relations', ' INDUSTRIAL & LABOUR RELATIONS ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-and-production-engineering', ' INDUSTRIAL & PRODUCTION ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-chemistry', ' INDUSTRIAL CHEMISTRY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-design', ' INDUSTRIAL DESIGN ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-engineering', ' INDUSTRIAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-mathematics', ' INDUSTRIAL MATHEMATICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-mathematics-applied-statistics', ' INDUSTRIAL MATHEMATICS / APPLIED STATISTICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-mathematics-computer', ' INDUSTRIAL MATHEMATICS / COMPUTER ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-microbiology', ' INDUSTRIAL MICROBIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-physics', ' INDUSTRIAL PHYSICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-physics-with-applied-geophysics', ' INDUSTRIAL PHYSICS WITH APPLIED GEOPHYSICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-physics-with-electronics-and-it-application', ' INDUSTRIAL PHYSICS WITH ELECTRONICS & IT APPLICATION ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-physics-with-renewable-energy', ' INDUSTRIAL PHYSICS WITH RENEWABLE ENERGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-production-engineering', ' INDUSTRIAL PRODUCTION ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-relations', ' INDUSTRIAL RELATIONS ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-relations-and-human-resources-management', ' INDUSTRIAL RELATIONS & HUMAN RESOURCES MANAGEMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-relations-and-personnel-management', ' INDUSTRIAL RELATIONS & PERSONNEL MANAGEMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('industrial-technical-education', ' INDUSTRIAL TECHNICAL EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('information-and-communication-engineering', ' INFORMATION & COMMUNICATION ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('information-and-communication-science', ' INFORMATION & COMMUNICATION SCIENCE ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('information-and-communication-technology', ' INFORMATION & COMMUNICATION TECHNOLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('information-and-communication-technology-engineering', ' INFORMATION & COMMUNICATION TECHNOLOGY ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('information-and-media-science', 'INFORMATION AND MEDIA SCIENCE', 8, 1, ''),
('information-and-media-technology', ' INFORMATION & MEDIA TECHNOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('information-resource-management', ' INFORMATION RESOURCE MANAGEMENT ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('information-science-and-media-studies', ' INFORMATION SCIENCE & MEDIA STUDIES ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('information-systems', ' INFORMATION SYSTEMS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('information-technology', ' INFORMATION TECHNOLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('insurance', ' INSURANCE ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('insurance-and-actuarial-science', ' INSURANCE & ACTUARIAL SCIENCE ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('intelligence-and-security-studies', ' INTELLIGENCE & SECURITY STUDIES ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('international-and-comparative-politics', ' INTERNATIONAL & COMPARATIVE POLITICS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('international-relations', ' INTERNATIONAL RELATIONS ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('international-relations-and-diplomacy', ' INTERNATIONAL RELATIONS & DIPLOMACY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('international-relations-and-strategic-studies', ' INTERNATIONAL RELATIONS & STRATEGIC STUDIES ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('international-studies', ' INTERNATIONAL STUDIES ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('international-studies-and-diplomacy', ' INTERNATIONAL STUDIES & DIPLOMACY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('islamic-sharia-law', ' ISLAMIC / SHARIA LAW ', 6, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('islamic-studies', ' ISLAMIC STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('kanuri', ' KANURI ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('land-surveying', ' LAND SURVEYING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('land-surveying-and-geoinformatics', ' LAND SURVEYING & GEOINFORMATICS ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('landscape-architecture', ' LANDSCAPE ARCHITECTURE ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('language-and-literature', ' LANGUAGE & LITERATURE ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('languages-and-linguistics', ' LANGUAGES & LINGUISTICS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('law', ' LAW ', 6, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('library-and-information-management', ' LIBRARY & INFORMATION MANAGEMENT ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('library-and-information-science', ' LIBRARY & INFORMATION SCIENCE ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('library-and-information-studies', ' LIBRARY & INFORMATION STUDIES ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('library-science', ' LIBRARY SCIENCE ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('linguistics', ' LINGUISTICS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('linguistics-and-african-languages', ' LINGUISTICS & AFRICAN LANGUAGES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('linguistics-and-communication-studies', ' LINGUISTICS & COMMUNICATION STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('linguistics-and-fulfulde', ' LINGUISTICS & FULFULDE ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('linguistics-and-kanuri', ' LINGUISTICS & KANURI ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('linguistics-and-nigerian-languages', ' LINGUISTICS & NIGERIAN LANGUAGES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('linguistics-and-urhobo', ' LINGUISTICS & URHOBO ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('linguistics-arabic', ' LINGUISTICS / ARABIC ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('linguistics-edo', ' LINGUISTICS / EDO ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('linguistics-english', ' LINGUISTICS / ENGLISH ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('linguistics-french', ' LINGUISTICS / FRENCH ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('linguistics-hausa', ' LINGUISTICS / HAUSA ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('linguistics-igbo', ' LINGUISTICS / IGBO ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('linguistics-yoruba', ' LINGUISTICS / YORUBA ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('literature-in-english', ' LITERATURE IN ENGLISH ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('livestock-production-technology', ' LIVESTOCK PRODUCTION TECHNOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('local-government-and-development-studies', ' LOCAL GOVERNMENT & DEVELOPMENT STUDIES ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('local-government-studies', ' LOCAL GOVERNMENT STUDIES ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('management', ' MANAGEMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds');
INSERT INTO `programs` (`id`, `name`, `college_id`, `honor_id`, `description`) VALUES
('management-information-system', ' MANAGEMENT INFORMATION SYSTEM ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('management-studies', ' MANAGEMENT STUDIES ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('management-technology', ' MANAGEMENT TECHNOLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('marine-biology', ' MARINE BIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('marine-biology-and-fisheries', ' MARINE BIOLOGY & FISHERIES ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('marine-economics-and-finance', ' MARINE ECONOMICS & FINANCE ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('marine-engineering', ' MARINE ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('marine-geology', ' MARINE GEOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('marine-science-and-technology', ' MARINE SCIENCE & TECHNOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('marketing', ' MARKETING ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('marketing-and-advertising', ' MARKETING & ADVERTISING ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mass-communication', ' MASS COMMUNICATION ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mass-communication-and-media-technology', ' MASS COMMUNICATION & MEDIA TECHNOLOGY ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mathematical-sciences', ' MATHEMATICAL SCIENCES ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mathematics', ' MATHEMATICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mathematics-and-economics', ' MATHEMATICS & ECONOMICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mathematics-and-statistics', ' MATHEMATICS & STATISTICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mathematics-computer-science', ' MATHEMATICS / COMPUTER SCIENCE ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mathematics-computer-science-education', ' MATHEMATICS / COMPUTER SCIENCE EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mathematics-statistics', ' MATHEMATICS / STATISTICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mathematics-statistics-education', ' MATHEMATICS / STATISTICS EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mathematics-with-computer-science', ' MATHEMATICS WITH COMPUTER SCIENCE ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mathematics-with-statistics', ' MATHEMATICS WITH STATISTICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mechanical-and-metallurgical-engineering', ' MECHANICAL & METALLURGICAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mechanical-engineering', ' MECHANICAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mechanical-production-engineering', ' MECHANICAL / PRODUCTION ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mechatronics-and-system-engineering', ' MECHATRONICS & SYSTEM ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('mechatronics-engineering', ' MECHATRONICS ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('media-and-communication-studies', ' MEDIA& COMMUNICATION STUDIES ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('medical-biochemistry', ' MEDICAL BIOCHEMISTRY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('medical-laboratory-science', ' MEDICAL LABORATORY SCIENCE ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('medical-rehabilitation', ' MEDICAL REHABILITATION ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('medicine-and-surgery', ' MEDICINE & SURGERY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('metallurgical-and-material-engineering', ' METALLURGICAL & MATERIAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('metallurgical-engineering', ' METALLURGICAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('meteorology', ' METEOROLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('meteorology-and-climate-change', ' METEOROLOGY & CLIMATE CHANGE ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('microbiology', ' MICROBIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('microbiology-and-biotechnology', ' MICROBIOLOGY & BIOTECHNOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('microbiology-and-industrial-biotechnology', ' MICROBIOLOGY & INDUSTRIAL BIOTECHNOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('military-history', ' MILITARY HISTORY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('military-science', 'MILITARY SCIENCE', 9, 1, ''),
('mining-engineering', ' MINING ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('modern-and-european-languages', ' MODERN & EUROPEAN LANGUAGES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('molecular-biology', ' MOLECULAR BIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('music', ' MUSIC ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('natural-and-environmental-science', ' NATURAL & ENVIRONMENTAL SCIENCE ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('natural-gas-engineering', 'NATURAL GAS ENGINEERING', 5, 1, ''),
('nautical-science', ' NAUTICAL SCIENCE ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('nigerian-languages', ' NIGERIAN LANGUAGES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('nursery-and-primary-education', ' NURSERY & PRIMARY EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('nursing-nursing-science', ' NURSING / NURSING SCIENCE ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('nutrition-and-consumers-services', ' NUTRITION & CONSUMERS SERVICES ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('nutrition-and-dietetics', ' NUTRITION & DIETETICS ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('oceanography', ' OCEANOGRAPHY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('office-and-information-management', ' OFFICE & INFORMATION MANAGEMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('operations-research', ' OPERATIONS RESEARCH ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('optometry', ' OPTOMETRY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('parasitology-and-entomology', ' PARASITOLOGY & ENTOMOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('pasture-and-range-management', ' PASTURE & RANGE MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('peace-and-conflict-studies', ' PEACE & CONFLICT STUDIES ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('peace-and-development-studies', ' PEACE & DEVELOPMENT STUDIES ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('peace-strategies-and-conflict-resolution', 'PEACE STRATEGIES AND CONFLICT RESOLUTION', 9, 1, ''),
('peace-studies', ' PEACE STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('peace-studies-and-conflict-resolution', ' PEACE STUDIES & CONFLICT RESOLUTION ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('performing-arts', ' PERFORMING ARTS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('personnel-management', ' PERSONNEL MANAGEMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('petrochemical-engineering', ' PETROCHEMICAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('petroleum-and-gas-engineering', ' PETROLEUM & GAS ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('petroleum-chemistry', ' PETROLEUM CHEMISTRY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('petroleum-engineering', ' PETROLEUM ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('pharmacology', ' PHARMACOLOGY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('pharmacology-and-therapeutics', ' PHARMACOLOGY & THERAPEUTICS ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('pharmacy', ' PHARMACY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('philosophy', ' PHILOSOPHY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('philosophy-and-religious-studies', ' PHILOSOPHY & RELIGIOUS STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('physical-and-health-education', ' PHYSICAL & HEALTH EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('physical-education', ' PHYSICAL EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('physical-sciences', ' PHYSICAL SCIENCES ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('physics', ' PHYSICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('physics-and-applied-physics', ' PHYSICS & APPLIED PHYSICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('physics-and-computer-electronic', ' PHYSICS & COMPUTER ELECTRONIC ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('physics-astrology', ' PHYSICS / ASTROLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('physics-electronics', ' PHYSICS ELECTRONICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('physics-industrial-physics', ' PHYSICS / INDUSTRIAL PHYSICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('physics-with-computational-modeling', ' PHYSICS WITH COMPUTATIONAL MODELING ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('physics-with-electronics', ' PHYSICS WITH ELECTRONICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('physics-with-solar-energy', ' PHYSICS WITH SOLAR ENERGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('physiology', ' PHYSIOLOGY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('physiotherapy', ' PHYSIOTHERAPY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('plant-biology', ' PLANT BIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('plant-biology-and-biotechnology', ' PLANT BIOLOGY & BIOTECHNOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('plant-breeding-and-seed-science', ' PLANT BREEDING & SEED SCIENCE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('plant-breeding-and-seed-technology', ' PLANT BREEDING & SEED TECHNOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('plant-physiology-and-crop-production', ' PLANT PHYSIOLOGY & CROP PRODUCTION ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('plant-science', ' PLANT SCIENCE ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('plant-science-and-biotechnology', ' PLANT SCIENCE & BIOTECHNOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('plant-science-and-crop-production', ' PLANT SCIENCE & CROP PRODUCTION ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('plant-science-and-forestry', ' PLANT SCIENCE & FORESTRY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('plant-science-and-microbiology', ' PLANT SCIENCE & MICROBIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('policy-and-administrative-studies', ' POLICY & ADMINISTRATIVE STUDIES ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('policy-and-strategic-studies', ' POLICY & STRATEGIC STUDIES ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('political-and-administrative-studies', ' POLITICAL & ADMINISTRATIVE STUDIES ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('political-science', ' POLITICAL SCIENCE ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('political-science-and-conflict-resolution', ' POLITICAL SCIENCE & CONFLICT RESOLUTION ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('political-science-and-defence-studies', ' POLITICAL SCIENCE & DEFENCE STUDIES ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('political-science-and-diplomacy', ' POLITICAL SCIENCE & DIPLOMACY ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('political-science-and-international-relations', ' POLITICAL SCIENCE & INTERNATIONAL RELATIONS ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('political-science-and-international-studies', ' POLITICAL SCIENCE & INTERNATIONAL STUDIES ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('political-science-and-public-administration', ' POLITICAL SCIENCE & PUBLIC ADMINISTRATION ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('political-science-international-law-and-diplomacy', ' POLITICAL SCIENCE / INTERNATIONAL LAW & DIPLOMACY ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('polymer-and-textile-engineering', ' POLYMER & TEXTILE ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('polymer-engineering', ' POLYMER ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('population-studies', ' POPULATION STUDIES ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('port-management', ' PORT MANAGEMENT ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('portuguese', ' PORTUGUESE ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('portuguese-english', ' PORTUGUESE / ENGLISH ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('pre-primary-and-primary-education', ' PRE-PRIMARY & PRIMARY EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('primary-and-elementary-education', ' PRIMARY & ELEMENTARY EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('primary-education-studies', ' PRIMARY EDUCATION STUDIES ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('procurement-management', 'PROCUREMENT MANAGEMENT', 1, 1, ''),
('production-engineering', ' PRODUCTION ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('prosthesis-and-orthopaedic-technology', ' PROSTHESIS & ORTHOPAEDIC TECHNOLOGY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('prosthetics-and-orthotics', 'PROSTETHICS AND ORTHOTICS', 7, 1, ''),
('psychology', ' PSYCHOLOGY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('psychology-education', 'PSYCHOLOGY EDUCATION', 4, 1, ''),
('public-administration', ' PUBLIC ADMINISTRATION ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('public-administration-and-local-government', ' PUBLIC ADMINISTRATION & LOCAL GOVERNMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('public-and-community-health', ' PUBLIC & COMMUNITY HEALTH ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('public-and-private-international-law', ' PUBLIC & PRIVATE INTERNATIONAL LAW ', 6, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('public-health', ' PUBLIC HEALTH ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('public-health-science', ' PUBLIC HEALTH SCIENCE ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('public-health-technology', ' PUBLIC HEALTH TECHNOLOGY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('public-relations-and-advertising', ' PUBLIC RELATIONS & ADVERTISING ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('pure-and-applied-biology', ' PURE & APPLIED BIOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('pure-and-applied-chemistry', ' PURE & APPLIED CHEMISTRY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('pure-and-applied-mathematics', ' PURE & APPLIED MATHEMATICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('pure-and-applied-physics', ' PURE & APPLIED PHYSICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('pure-and-industrial-chemistry', ' PURE & INDUSTRIAL CHEMISTRY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('pure-and-industrial-physics', ' PURE & INDUSTRIAL PHYSICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('pure-chemistry', ' PURE CHEMISTRY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('pure-physics', ' PURE PHYSICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('quantity-surveying', ' QUANTITY SURVEYING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('radiography', ' RADIOGRAPHY ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('radiography-and-radiation-science', ' RADIOGRAPHY & RADIATION SCIENCE ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('religions-and-african-culture', ' RELIGIONS & AFRICAN CULTURE ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('religious-and-cultural-studies', ' RELIGIOUS & CULTURAL STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('religious-and-human-relations', ' RELIGIOUS & HUMAN RELATIONS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('religious-studies', ' RELIGIOUS STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('remote-sensing-and-geosciences-information-system', ' REMOTE SENSING & GEOSCIENCES INFORMATION SYSTEM ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('russian', ' RUSSIAN ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('russian-with-french-german', ' RUSSIAN WITH FRENCH / GERMAN ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('science-education', ' SCIENCE EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('science-laboratory-technology', ' SCIENCE LABORATORY TECHNOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('secretarial-administration', ' SECRETARIAL ADMINISTRATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('secretarial-administration-and-education', ' SECRETARIAL ADMINISTRATION & EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('secretarial-education', ' SECRETARIAL EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('shipping-and-maritime-technology', ' SHIPPING & MARITIME TECHNOLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('social-justice', ' SOCIAL JUSTICE ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('social-work', ' SOCIAL WORK ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('sociology', ' SOCIOLOGY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('sociology-and-anthropology', ' SOCIOLOGY & ANTHROPOLOGY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('software-engineering', ' SOFTWARE ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('soil-and-environmental-management', ' SOIL & ENVIRONMENTAL MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('soil-science', ' SOIL SCIENCE ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('soil-science-and-land-agro-climatology', ' SOIL SCIENCE & LAND AGRO-CLIMATOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('soil-science-and-land-management', ' SOIL SCIENCE & LAND MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('soil-science-and-technology', ' SOIL SCIENCE & TECHNOLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('soil-science-management', ' SOIL SCIENCE MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('special-education', ' SPECIAL EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('sport-science', ' SPORT SCIENCE ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('statistics', ' STATISTICS ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('statistics-computer-science-education', ' STATISTICS / COMPUTER SCIENCE EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('statistics-education', ' STATISTICS EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('statistics-with-demography', ' STATISTICS WITH DEMOGRAPHY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('structural-engineering', ' STRUCTURAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('surveying-and-geoinformatics', ' SURVEYING & GEOINFORMATICS ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('systems-engineering', ' SYSTEMS ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('taxation', ' TAXATION ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('technical-education', ' TECHNICAL EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('technological-management', ' TECHNOLOGICAL MANAGEMENT ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('telecommunication-engineering', ' TELECOMMUNICATION ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('telecommunication-management', ' TELECOMMUNICATION MANAGEMENT ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('telecommunication-science', ' TELECOMMUNICATION SCIENCE ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('textile-science-and-technology', ' TEXTILE SCIENCE & TECHNOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('theatre-and-film-studies', ' THEATRE & FILM STUDIES ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('theatre-and-media-arts', ' THEATRE & MEDIA ARTS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('theatre-and-performing-arts', ' THEATRE & PERFORMING ARTS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('theatre-arts', ' THEATRE ARTS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('theology', ' THEOLOGY ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('tourism-and-event-management', ' TOURISM & EVENT MANAGEMENT ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('tourism-studies', ' TOURISM STUDIES ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('transport-and-logistics-management', ' TRANSPORT & LOGISTICS MANAGEMENT ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('transport-and-tourism', ' TRANSPORT & TOURISM ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('transport-logistics-management', ' TRANSPORT LOGISTICS MANAGEMENT ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('transport-management', ' TRANSPORT MANAGEMENT ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('transport-management-technology', ' TRANSPORT MANAGEMENT TECHNOLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('transport-planning-and-management', ' TRANSPORT PLANNING & MANAGEMENT ', 9, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('transport-planning-and-management-and-education', ' TRANSPORT PLANNING & MANAGEMENT & EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('urban-and-regional-planning', ' URBAN & REGIONAL PLANNING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('veterinary-medicine', ' VETERINARY MEDICINE ', 7, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('visual-and-applied-arts', ' VISUAL & APPLIED ARTS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('visual-arts-and-technology', ' VISUAL ARTS & TECHNOLOGY ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('vocational-and-technical-education', ' VOCATIONAL & TECHNICAL EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('vocational-education', 'VOCATIONAL EDUCATION', 4, 1, ''),
('vocational-industrial-education', ' VOCATIONAL INDUSTRIAL EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('water-and-irrigation-engineering', 'WATER AND IRRIGATION ENGINEERING', 5, 1, ''),
('water-resources-and-environmental-engineering', ' WATER RESOURCES & ENVIRONMENTAL ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('water-resources-aquaculture-and-fisheries-technology', ' WATER RESOURCES AQUACULTURE & FISHERIES TECHNOLOGY ', 1, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('water-resources-management-and-agrometeorology', ' WATER RESOURCES MANAGEMENT & AGROMETEOROLOGY ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('wildlife-management', ' WILDLIFE MANAGEMENT ', 2, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('wood-production-engineering', ' WOOD PRODUCTION ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('wood-products-engineering', ' WOOD PRODUCTS ENGINEERING ', 5, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('woodwork-education', ' WOODWORK / EDUCATION ', 4, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('yoruba', ' YORUBA ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('yoruba-and-communication-arts', ' YORUBA & COMMUNICATION ARTS ', 3, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('zoology', ' ZOOLOGY ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('zoology-and-aquaculture', ' ZOOLOGY & AQUACULTURE ', 8, 1, 'asdfghjkjhgfdsasdfghgfdsasdfgfdsdfgfdsasdfgfds'),
('zoology-and-environmental-biology', ' ZOOLOGY & ENVIRONMENTAL BIOLOGY ', 8, 1, 'xxx');
